$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment
endpoint_name: diabetes-endpoint20221228
model: azureml:diabetes-sklearn-mlflow-model@latest
instance_type: Standard_DS2_v2
instance_count: 1