name: Trygger echo on pull request

on:
  [pull_request]

jobs:
  echojob:
    runs-on: ubuntu-latest
    steps:
    - name: Echo step
      run: |
        echo "Will add code checks here in next challenge"


