name: MLenvflow

on:
  push:
    branches: [ main ]

jobs:
  experiment:
    runs-on: ubuntu-latest
    environment: dev-env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --resource-group mlopsgroup --workspace-name mlopsws --stream True
  production:
    needs: experiment
    runs-on: ubuntu-latest
    environment: prod-env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml --resource-group mlopsgroup --workspace-name mlopsws --stream True