name: Model deployment

on:
  push:
    branches: [ main ]

jobs:
  production:
    runs-on: ubuntu-latest
    environment: prod-env
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml --resource-group mlopsgroup --workspace-name mlopsws --stream
        JOB_NAME=$(az ml job list --resource-group mlopsgroup --workspace-name mlopsws --query "[0].name" | tr -d '"')
        az ml model create --name "diabetes-sklearn-mlflow-model" \
                   --type "mlflow_model" \
                   --resource-group mlopsgroup --workspace-name mlopsws \
                   --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"
        az ml online-endpoint create --name diabetes-endpoint202212283 \
                   -f endpoints/create-endpoint.yaml --resource-group mlopsgroup --workspace-name mlopsws
        az ml online-deployment create --name mlflow-deployment --endpoint diabetes-endpoint202212283 \
                   -f endpoints/mlflow-deployment.yaml --all-traffic --resource-group mlopsgroup --workspace-name mlopsws
        

